name: Stock Alert Bot

on:
  schedule:
    - cron: "*/45 12-23 * * 1-5"  # every 45 min between 7am–6pm EST, Mon–Fri
  workflow_dispatch:  # allows manual triggering

jobs:
  run-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Stock Alert Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
          NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
          FORCE_TEST_ALERT: ${{ secrets.FORCE_TEST_ALERT }}
        run: python stock_alert_bot.py
